{{--<x-app-layout>--}}
{{--    <x-slot name="header">--}}
{{--        <h2 class="font-semibold text-xl text-gray-800 leading-tight">--}}
{{--            {{ __('Two-Factor Authentication Verification') }}--}}
{{--        </h2>--}}
{{--    </x-slot>--}}

{{--    <div class="flex flex-col items-center justify-center min-h-screen bg-gray-100">--}}
{{--        <div class="max-w-md w-full px-6 py-8 bg-white shadow-md rounded-lg">--}}

{{--            <h2 class="mt-6 text-3xl font-semibold text-center text-gray-800">Two-Factor Authentication--}}
{{--                Verification</h2>--}}

{{--            <p class="mt-2 text-sm text-center text-gray-600">--}}
{{--                Please enter the security code generated by the authenticator app on your device.--}}
{{--            </p>--}}

{{--            <!-- Validation Errors -->--}}
{{--            @if ($errors->any())--}}
{{--                <div class="mt-4">--}}
{{--                    <div class="font-medium text-red-600">Whoops! Something went wrong.</div>--}}

{{--                    <ul class="mt-3 list-disc list-inside text-sm text-red-600">--}}
{{--                        @foreach ($errors->all() as $error)--}}
{{--                            <li>{{ $error }}</li>--}}
{{--                        @endforeach--}}
{{--                    </ul>--}}
{{--                </div>--}}
{{--            @endif--}}

{{--            <form method="POST" action="{{ route('verify.2fa.submit') }}" class="mt-6">--}}
{{--                @csrf--}}

{{--                <!-- Security Code -->--}}
{{--                <div>--}}
{{--                    <label for="security_code" class="block mb-2 text-sm font-medium text-gray-600">Security--}}
{{--                        Code</label>--}}
{{--                    <input id="security_code"--}}
{{--                           class="block w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"--}}
{{--                           type="text" name="security_code" required autofocus>--}}
{{--                </div>--}}

{{--                <div class="mt-6">--}}
{{--                    <button type="submit"--}}
{{--                            class="w-full px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-500 focus:outline-none focus:bg-indigo-500">--}}
{{--                        Verify--}}
{{--                    </button>--}}
{{--                </div>--}}
{{--            </form>--}}

{{--            <div class="flex items-center justify-end mt-4">--}}
{{--                <a class="text-sm text-indigo-600 hover:text-indigo-500" href="{{ route('dashboard') }}">--}}
{{--                    Cancel and Return to Dashboard--}}
{{--                </a>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
{{--</x-app-layout>--}}
